name: "[2] Auto-PR develop → main"

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    permissions:
      contents: write
      pull-requests: write
    name: Crear PR contra main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar usuario git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Actualizar rama temporal
        run: |
          git fetch origin main
          git checkout -B sync/develop-to-main origin/main
          git merge origin/develop --no-ff --no-edit

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: sincronizar develop → main'
          branch: sync/develop-to-main
          base: main
          title: '🔄 Sincronizar develop → main'
          body: |
            Este PR se ha generado automáticamente tras el push a **develop**.
            Actualiza los cambios de develop para mantener main al día.
          labels: automated, sync